name: 'Terraform GitHub Actions'

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  Deploy_Resources:
    name: 'Terraform Deploy'
    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v4

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION }}
    
    - name: Terraform Install
      uses: hashicorp/setup-terraform@v3
      
    - name: Terraform fmt
      id: fmt
      run: | 
        terraform --version
        terraform fmt
      continue-on-error: true
      
    - name: Terraform Init
      id: init
      run: terraform init 
      
    - name: Terraform Validate
      id: validate
      run: terraform validate -no-color 
      
    - name: Terraform Plan
      id: plan
      run: terraform plan -no-color
      continue-on-error: true
      
    - name: Terraform Apply
      id: Apply
      run: terraform apply -auto-approve
      continue-on-error: true
      
    #- name: Terraform Destroy
    #  id: Destory
    #  run: terraform destroy -auto-approve
    #  continue-on-error: true
    
    
      run: terraform apply -auto-approve -input=false
